using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Forms.UI;

[GenerateTypedNameReferences]
public sealed partial class TextFormField : BoxContainer, IFormField
{
    public Action? OnFieldSet { get; }

    private string _fieldName = string.Empty;

    public string FieldName
    {
        get => _fieldName;
        set
        {
            _fieldName = value;
            FieldNameLabel.Text = value;
        }
    }

    public object Value
    {
        get => FieldInput.Text;
        set => FieldInput.Text = (string) value;
    }

    public TextFormField()
    {
        RobustXamlLoader.Load(this);
        FieldInput.OnTextEntered += _ => OnFieldSet!();
    }
}
