using Content.Shared.Forms;
using Robust.Client.AutoGenerated;

namespace Content.Client.Forms.UI.Windows;

[GenerateTypedNameReferences]
[FormDialog(typeof(TextDialogFormState))]
public sealed partial class TextDialogFormWindow : FormWindow
{}
